layer_descriptions = {
    "conv2d": "This is first convolutional layer that scans the input sketch with small filters to find basic features like edges or shapes. The brighter parts show where I am detecting simple features like sharp lines or basic outlines in the sketch.",
    "max_pooling2d": "This is a pooling layer that reduces the size of the image by focusing on the most important features. The light areas highlight the most important parts of the sketch, simplifying the image while keeping the most relevant features.",
    "conv2d_1": "This is second convolutional layer that looks for more complex features in the sketch, building on the simple patterns identified by the first layer. You'll see areas where I detect more detailed patterns or shapes that make up parts of the object in the sketch.",
    "max_pooling2d_1": "This is another pooling layer that further reduces the size of the image, allowing the model to focus even more on the key features. The light areas represent the most important regions of the sketch that the pooling layer keeps, while simplifying the rest of the image.",
    "conv2d_2": "This is a third convolutional layer that looks for even more advanced patterns based on what I have already learned from the previous layers. The activation image for this layer highlights the parts of the sketch where I detect high-level features.",
    "flatten": "This layer flattens the 2D features into a simple 1D list of numbers - a format that I can use for decision-making in the next layers.",
    "dense": "This is a fully connected (dense) layer that links all the features together. Based on the patterns I have learned from the previous layers, I start to combine the information to make predictions about what the sketch represents. The brighter areas show where I am focusing on specific features I have learned to recognize.",
    "dense_1": "This is the final dense layer, where I makes my decision (apple (left) / pear (right)). I look at all the features learned from the previous layers and pick the most likely outcome."
}